name: Auto-Deploy to Home Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Windows Server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        debug: true
        script: |
          cmd.exe /c "
          echo === Starting deployment ===
          echo Current directory: %cd%
          cd /d C:\Users\calss\GitHub\Cardfight_companion
          if %errorlevel% neq 0 (
            echo ERROR: Failed to navigate to project directory
            exit /b 1
          )
          echo Successfully navigated to: %cd%
          git status
          git pull origin main
          if %errorlevel% neq 0 (
            echo ERROR: Git pull failed
            exit /b 1
          )
          update.bat
          "
