name: Auto-Deploy to Home Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Windows Server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        debug: true
        script: |
          set -e  # Exit on any error
          echo "=== Starting deployment ==="
          echo "Current directory: $(pwd)"
          echo "Current user: $(whoami)"
          echo ""
          
          echo "=== Testing path access ==="
          ls -la /c/Users/ || echo "Cannot list /c/Users/"
          ls -la "/c/Users/calss" || echo "Cannot access calss directory"
          ls -la "/c/Users/calss/GitHub" || echo "Cannot access GitHub directory"
          
          echo "=== Navigating to project directory ==="
          TARGET_DIR="/c/Users/calss/GitHub/Cardfight_companion"
          echo "Attempting to access: $TARGET_DIR"
          
          if [ -d "$TARGET_DIR" ]; then
            echo "Directory exists, changing to it..."
            cd "$TARGET_DIR"
            echo "Successfully navigated to: $(pwd)"
          else
            echo "ERROR: Directory $TARGET_DIR does not exist"
            echo "Looking for alternative paths..."
            find /c -name "Cardfight_companion" -type d 2>/dev/null || echo "Project not found anywhere in /c"
            exit 1
          fi
          
          echo "=== Directory contents ==="
          ls -la
          
          echo "=== Git status ==="
          git status || echo "Git status failed"
          
          echo "=== Git pull ==="
          git pull origin main || echo "Git pull failed"
          
          echo "=== Script completed ==="
