name: Auto-Deploy to Home Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Windows Server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        debug: true
        script: |
          powershell.exe -Command "
          Write-Host '=== Starting deployment ==='
          Set-Location 'C:\Users\calss\GitHub\Cardfight_companion'
          if (-not $?) { Write-Error 'Failed to navigate to directory'; exit 1 }
          Write-Host 'Current directory:' (Get-Location)
          git status
          git pull origin main
          if (-not $?) { Write-Error 'Git pull failed'; exit 1 }
          & '.\update.bat'
          if (-not $?) { Write-Error 'update.bat failed'; exit 1 }
          Write-Host '=== Deployment completed successfully ==='
          "
