name: Auto-Deploy to Home Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Test Basic Commands
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        debug: true
        script: |
          pwd
          whoami
          echo "Listing current directory contents:"
          ls -la
          echo "Checking if GitHub directory exists:"
          ls -la GitHub 2>&1 || echo "GitHub directory not found or not accessible"
          echo "Attempting to change directory:"
          cd GitHub/Cardfight_companion 2>&1 || echo "Failed to cd to GitHub/Cardfight_companion"
          echo "After cd attempt, current directory is:"
          pwd
          echo "Script completed"
