name: Auto-Deploy to Home Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Windows Server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        debug: true
        script: |
          powershell -Command "
          Write-Host '=== Starting deployment ==='
          Set-Location 'C:\Users\calss\GitHub\Cardfight_companion'
          Write-Host 'Successfully navigated to:' (Get-Location)
          Write-Host '=== Pulling latest changes ==='
          git pull origin main
          Write-Host '=== Running update.bat ==='
          if (Test-Path 'update.bat') {
            & .\update.bat
            Write-Host 'update.bat completed successfully'
          } else {
            Write-Error 'update.bat not found'
            exit 1
          }
          Write-Host '=== Deployment completed successfully ==='
          "
